/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab8test;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String arg[]) {
    	System.out.println("hahaha");
    	System.out.println("xixixi");
    }
}
